### ISSUE TITLE
ConnectError

### ISSUE THREAD

**Issue by Zonalds** [pyepye/django-amplitude#1]
I would get something like:

```
Request Method: | GET
-- | --
http://127.0.0.1:8000/
2.2.12
ConnectError
[Errno 101] Network is unreachable

```
Here is how my setting.py looks:

# Amplitude Setings

AMPLITUDE_API_KEY = '1xxxxxxxxxxxxxxxx0' 

AMPLITUDE_INCLUDE_USER_DATA = True
AMPLITUDE_INCLUDE_GROUP_DATA = True

The installed apps

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'person',
    'highlights',
    'amplitude',

    
The middleware

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'amplitude.middleware.SessionInfo',
    'amplitude.middleware.SendPageViewEvent',
]

I ran migrate right after the set up. Any idea why it isn't working?

**Comment by pyepye** [comment]
Hi @Zonalds 

Sorry a little late seeing this message.

A `ConnectError` means that the network is unreachable and there is problem with the connection to the Internet, normally due to network or proxy settings. [It's raised from httpx](https://github.com/encode/httpx/blob/d7aa6e018913349166fba64cd5f3a9daba7364fb/httpx/_exceptions.py#L135-L138)
```
class ConnectError(NetworkError):
    """
    Failed to establish a connection.
    """
```

It's not an error with the request itself or a response from Amplitude as [all HTTPErrors are re-raised as `AmplitudeException`](https://github.com/pyepye/django-amplitude/blob/384498a04f3d06db9b710cb511b535859cb9fcd4/amplitude/amplitude.py#L61-L64
)

Are you able to make other requests the outbound internet?  For example what happens if you try and `cURL` the amplitude URL?
```
$ curl https://api.amplitude.com/2/httpapi
```
You should get a 400 error from Amplitude not a network timeout:
```
$ curl https://api.amplitude.com/2/httpapi
{"code":400,"error":"Missing request body"}
```

**Comment by pyepye** [comment]
Hi @Zonalds 

We have not heard back from you so I'm going to close this issue. Please re-open this issue or create a new one if needed.
